defaults: &defaults
  app_name: "爆笑集中营"
  admin_emails:
    - "xxxxxx@xxxxx.com"

development:
  <<: *defaults
  domain_url: 'http://127.0.0.1:3000'

test:
  <<: *defaults

production:
  <<: *defaults
  domain_url: 'http://baoxiao.wakmj.com'  
